[package]
name = "lab-intent-classifier"
version = "0.1.0"
edition = "2021"

[dependencies]
fasttext = "0.7.8"
vtext = "0.2.0"
rust-stemmers = "=1.2.0"
stopwords = "0.1.1"
itertools = "0.14.0"
csv = "1.3.1"
serde = "1.0.217"
serde_derive = "1.0.217"
